language: php
compiler:
  - gcc
addons:
  apt:
    packages:
      - valgrind
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1
    - CONF="without-cmark-coverage"
    - RULE="all"
    - DEF="-q --show-diff"
    - MEMCHECK="-m --show-mem"
  matrix:
    - OPCACHE=0 TEST_PHP_ARGS="$DEF"
    - OPCACHE=1 TEST_PHP_ARGS="$DEF"
    - OPCACHE=0 TEST_PHP_ARGS="$DEF $MEMCHECK"
    - OPCACHE=0 TEST_PHP_ARGS="$DEF" CONF="with-cmark-coverage" RULE="cmark-test-coverage-travis"

matrix:
  allow_failures:
    - php: nightly
      env: OPCACHE=0 TEST_PHP_ARGS="$DEF $MEMCHECK"

before_install:
  - test $CONF != "with-cmark-coverage" || pip install --user cpp-coveralls

before_script:
  - echo "variables_order=EGPCS"                 >> $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - echo                                          > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
  - echo "extension=cmark.so"                     > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/cmark.ini
  - echo "opcache.enable_cli=$OPCACHE"            > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/opcache.ini
  - echo "opcache.optimization_level=0x7FFEBFFF" >> $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/opcache.ini
  - git clone --depth=1 https://github.com/commonmark/cmark $HOME/libcmark-src
  - cd $HOME/libcmark-src
  - mkdir $HOME/libcmark
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/libcmark
  - make
  - make install

script:
  - cd $TRAVIS_BUILD_DIR
  - phpize
  - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
  - ./configure --$CONF --with-cmark=$HOME/libcmark
  - make $RULE
  - make install
  - php run-tests.php -P

after_success:
  - test $CONF != "with-cmark-coverage" || coveralls -b $TRAVIS_BUILD_DIR -E Zend --gcov-options '\-lp'
